// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiN5rpzGTAqb_6dvfYo4dOZ-SKkVqxdF8',
    appId: '1:938236458983:web:3a16c55ac206990de4ef42',
    messagingSenderId: '938236458983',
    projectId: 'deepfector',
    authDomain: 'deepfector.firebaseapp.com',
    storageBucket: 'deepfector.appspot.com',
    measurementId: 'G-YZQB45BQG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN_Cd-eOm-mgs8HESphK_nnk5V0-3HTSU',
    appId: '1:938236458983:android:5b317675df0daefde4ef42',
    messagingSenderId: '938236458983',
    projectId: 'deepfector',
    storageBucket: 'deepfector.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT0ZmMZ4H8gY-SZAPd9_EZusmA7xC5doY',
    appId: '1:938236458983:ios:0b162a92a8b26fdbe4ef42',
    messagingSenderId: '938236458983',
    projectId: 'deepfector',
    storageBucket: 'deepfector.appspot.com',
    iosClientId: '938236458983-cg0blbuajgjfc1rp8u02htfpqlac7sks.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT0ZmMZ4H8gY-SZAPd9_EZusmA7xC5doY',
    appId: '1:938236458983:ios:0b162a92a8b26fdbe4ef42',
    messagingSenderId: '938236458983',
    projectId: 'deepfector',
    storageBucket: 'deepfector.appspot.com',
    iosClientId: '938236458983-cg0blbuajgjfc1rp8u02htfpqlac7sks.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiN5rpzGTAqb_6dvfYo4dOZ-SKkVqxdF8',
    appId: '1:938236458983:web:ceaac54606413151e4ef42',
    messagingSenderId: '938236458983',
    projectId: 'deepfector',
    authDomain: 'deepfector.firebaseapp.com',
    storageBucket: 'deepfector.appspot.com',
    measurementId: 'G-R20X4W51LC',
  );

}